name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop
        shell: powershell
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        shell: powershell
        run: flutter pub get

      - name: Build Windows Release
        shell: powershell
        run: |
          $env:CMAKE_POLICY_VERSION_MINIMUM="3.5"
          flutter build windows --release

      - name: Add Visual C++ Runtime DLLs
        shell: powershell
        run: |
          $release = "build\windows\x64\runner\Release"

          $vcRedistRoot = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC"

          if (-not (Test-Path $vcRedistRoot)) {
            Write-Error "Visual C++ Redistributable folder not found"
            exit 1
          }

          $latest = Get-ChildItem $vcRedistRoot -Directory |
                    Sort-Object Name -Descending |
                    Select-Object -First 1

          $crtPath = Join-Path $latest.FullName "x64\Microsoft.VC143.CRT"

          if (-not (Test-Path $crtPath)) {
            Write-Error "Microsoft.VC143.CRT folder not found"
            exit 1
          }

          Copy-Item "$crtPath\*.dll" $release -Force

          Write-Host "Visual C++ Runtime DLLs copied successfully"

      - name: Verify Windows Release
        shell: powershell
        run: |
          $release = "build\windows\x
