// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOJw0_HBNUYlyTMfYofFVMOiu3X0jQPw',
    appId: '1:836127423684:web:fd476d6f67da62ee12dd91',
    messagingSenderId: '836127423684',
    projectId: 'distribution-load-register',
    authDomain: 'distribution-load-register.firebaseapp.com',
    storageBucket: 'distribution-load-register.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3_CDIBg1l7FohtYfmXB4tCBrPque7Ho',
    appId: '1:836127423684:android:095e684ec5cbd3c612dd91',
    messagingSenderId: '836127423684',
    projectId: 'distribution-load-register',
    storageBucket: 'distribution-load-register.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXOJw0_HBNUYlyTMfYofFVMOiu3X0jQPw',
    appId: '1:836127423684:web:fd476d6f67da62ee12dd91',
    messagingSenderId: '836127423684',
    projectId: 'distribution-load-register',
    authDomain: 'distribution-load-register.firebaseapp.com',
    storageBucket: 'distribution-load-register.firebasestorage.app',
  );
}
