name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop
        shell: powershell
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        shell: powershell
        run: flutter pub get

      - name: Build Windows Release
        shell: powershell
        run: |
          $env:CMAKE_POLICY_VERSION_MINIMUM="3.5"
          flutter build windows --release

      - name: Verify Windows Release
        shell: powershell
        run: |
          $release = "build\windows\x64\runner\Release"

          if (-not (Test-Path $release)) {
            Write-Error "Windows Release folder not found"
            exit 1
          }

          if (-not (Test-Path "$release\distribution_load_register_final.exe")) {
            Write-Error "EXE file not found"
            exit 1
          }

          Write-Host "EXE found successfully"

      - name: Upload Windows Program
        uses: actions/upload-artifact@v4
        with:
          name: Distribution-Load-Register-Windows-x64-Compatible
          path: build/windows/x64/runner/Release/
          retention-days: 30
          if-no-files-found: error
